services:
  postgres:
    image: postgres:15-alpine
    container_name: zabbix-postgres
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./dados:/var/lib/postgresql/data
  
    networks:
      - zabbix-net

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-7.2-latest
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
    volumes:
      - "./config/zabbix_server.conf:/etc/zabbix/zabbix_server.conf"
    depends_on:
      - postgres
    ports:
      - "10051:10051"
    networks:
      - zabbix-net

  zabbix-web:
    image: zabbix/zabbix-web-apache-pgsql:alpine-7.2-latest
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: America/Bahia     
    depends_on:
      - zabbix-server
    ports:
      - "8080:8080"
    networks:
      - zabbix-net

  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-7.2-latest
    container_name: zabbix-agent
    environment:
      ZBX_SERVER_HOST: zabbix-server
      HOSTNAME: zabbix-agent
    depends_on:
      - zabbix-server
    ports:
      - "10050:10050"
    volumes:
      - ./config/zabbix_agentd.conf:/etc/zabbix/zabbix_agentd.conf
    networks:
      - zabbix-net
volumes:
  pgdata:
    driver: local
  grafana-data:
    driver: local

networks:
  zabbix-net:
    driver: bridge